server:
  port: 8080

spring:
  application:
    name: negocio
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: newera

app:
  defaults:
    foto-perfil: https://65.38.98.77/assets/defaults/fotoGenerica.png
    foto-credencial: https://65.38.98.77/assets/defaults/credencial.png
